# Generated by Django 5.1.2 on 2024-11-16 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_home_delete_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='home',
            name='types_of_property',
            field=models.CharField(choices=[('cabins', 'Cabins'), ('icons', 'Icons'), ('amazing views', 'Amazing views'), ('beachfront', 'Beachfront'), ('skiing', 'Skiing'), ('container', 'Containers'), ('treehouses', 'Treehouses'), ('mansions', 'Mansions'), ('tiny homes', 'Tiny Homes'), ('amazing pools', 'Amazing pools'), ('play', 'Play'), ('countryside', 'CountrySide'), ('farms', 'Farms'), ('camping', 'Camping'), ('rooms', 'Rooms')], default='random', max_length=200),
        ),
    ]
