# Generated by Django 5.1.2 on 2024-11-16 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_home_owner_alter_home_types_of_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='uploads/')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='api.home')),
            ],
        ),
    ]
