# Generated by Django 5.1.2 on 2024-11-16 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_homeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeimage',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home', to='api.home'),
        ),
        migrations.AlterField(
            model_name='homeimage',
            name='images',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
