# Generated by Django 5.1.2 on 2024-11-16 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_homeimage_home_alter_homeimage_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.home')),
            ],
            options={
                'unique_together': {('customer', 'home', 'start_date', 'end_date')},
            },
        ),
    ]
