# Generated by Django 5.1.2 on 2024-11-17 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='number_of_guests',
            field=models.ImageField(default=1, upload_to='', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='home',
            name='base_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='total_number_of_guest',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2000)]),
        ),
    ]
