# Generated by Django 5.1.2 on 2024-11-17 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_bookings_number_of_guests_home_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='number_of_guests',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
