# Generated by Django 5.1.2 on 2024-11-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_bookings_number_of_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='base_price',
            field=models.FloatField(default=2000),
        ),
    ]
