# Generated by Django 5.1.2 on 2024-11-17 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_home_base_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='customer',
            new_name='guest',
        ),
        migrations.AlterUniqueTogether(
            name='bookings',
            unique_together={('guest', 'home', 'start_date', 'end_date')},
        ),
    ]
