# Generated by Django 5.1.2 on 2024-11-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_home_country_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='images',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
