# Generated by Django 5.1.2 on 2024-11-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_home_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='description',
            field=models.TextField(default='nice', max_length=256),
            preserve_default=False,
        ),
    ]
