# Generated by Django 5.1.2 on 2025-01-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_home_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookings',
            unique_together={('home', 'start_date', 'end_date')},
        ),
    ]
