# Generated by Django 5.1.2 on 2025-02-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_bookings_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together={('guest', 'home')},
        ),
    ]
