# Generated by Django 5.1.2 on 2025-02-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_profile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='User',
            new_name='user',
        ),
    ]
