# Generated by Django 5.1.2 on 2025-04-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_user_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='airconditioner',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='exteriorcam',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='fireext',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='freeparking',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='fridge',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='heating',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='microwave',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='roomservices',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='smokealarm',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='wifi',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
