# Generated by Django 5.1.2 on 2025-05-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_profileimage_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='img',
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default='owner', null=True),
        ),
    ]
