# Generated by Django 5.1.2 on 2025-05-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_profile_img_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
