# Generated by Django 5.1.2 on 2025-05-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='documents',
        ),
    ]
